upyun-exporter
douban/upyun-exporter pull request #2
Opened 2022-08-19 01:43 UTC by NightWindD

2022-08-19 01:53 UTC, LeoQuote requested changes

2022-08-19 01:53 UTC, LeoQuote commented on httpRequest/httpRequest.go
> +type HealthDegreeList struct {
health degree = 健康度？ 翻译太蹩脚了

2022-08-19 01:53 UTC, LeoQuote commented on httpRequest/httpRequest.go
> +		Two00  int64 `json:"_200"`
这下面的变量名是因为变量不能以数字开头所以这样取名吧，你觉得 Code2xx 之类的如何？

2022-08-19 01:53 UTC, LeoQuote commented on main.go
> +	startTime := flag.String("startTime", os.Getenv("UpYun_startTime"), "upYun startTime")
starttime 和endtime 是用户传值？ 时间戳？我以后export出来的指标都是同一时间段的？这不现实吧

2022-08-19 06:41 UTC, LeoQuote commented on httpRequest/httpRequest.go
> +	var healthDegree AccountHealthList
这里的"健康度"也没改

2022-08-19 06:43 UTC, LeoQuote commented on httpRequest/httpRequest.go
> +	startTime := time.Now().Add(-time.Minute * time.Duration(rangeTime)).Format("2006-01-02:15:04:05")
为啥要 add 负值? 没看到 https://pkg.go.dev/time#Time.Sub 吗?

2022-08-19 06:45 UTC, LeoQuote commented on main.go
> +	delayTime := flag.Int64("delayTime", 60, "upYun delayTime")
你能在这里更详细的解释 rangeTime 和 delayTime 是什么吗? 这个参数单位是什么, 传进去之后有什么用之类的

2022-08-19 06:48 UTC, LeoQuote commented
里面的所有"健康度"的术语都改成类似"返回码" 的术语

2022-08-19 07:21 UTC, NightWindD commented on httpRequest/httpRequest.go
> +	startTime := time.Now().Add(-time.Minute * time.Duration(rangeTime)).Format("2006-01-02:15:04:05")
这个time包Add和Sub应该是两个不同的函数吧 Add用于计算某个时间之前和之后的时间点 Sub用于计算两个时间差 我要传进去一个时间点 所以应该用add “+ -”是代表是前后 应该不是加减这种意思

2022-08-19 10:01 UTC, LeoQuote commented on httpRequest/httpRequest.go
> +	startTime := time.Now().Add(-time.Minute * time.Duration(rangeTime)).Format("2006-01-02:15:04:05")
嗯, 你说得对, 是我看错了

2022-08-19 10:07 UTC, LeoQuote commented on main.go
> +	delayTime := flag.Int64("delayTime", 60, "time-delay of the endTime")
```suggestion
        delayTime := flag.Int64("delayTime", 60, "时间偏移量, 结束时间=now-delay_seconds")
	rangeTime := flag.Int64("rangeTime", 3000, "选取时间范围, 开始时间=now-range_seconds, 结束时间=now")
```

2022-08-19 10:08 UTC, LeoQuote commented on main.go
> +	tickerTime := flag.Int("tickerTime", 10,  "tickerTime")
```suggestion
	tickerTime := flag.Int("tickerTime", 10,  "刷新域名列表间隔时间")
```

2022-08-19 10:40 UTC, LeoQuote commented
cdn 的 所有状态码都要导出, 回源状态码也要全部导出, 2xx , 3xx, 4xx, 5xx 也要有

2022-08-22 08:02 UTC, LeoQuote requested changes
回源和 cdn 的状态码都要全部导出, 回源和 cdn 的 4xx 5xx 等也要计算出来后导出.

由于状态码比较多, 目前指标有点太多了, 请合理使用 label 减少指标的数量

2022-08-22 08:02 UTC, LeoQuote commented on exporter/exporter.go
> +const cdnNameSpace = "upYun"
```suggestion
const cdnNameSpace = "upyun"
```

2022-08-22 08:02 UTC, LeoQuote commented on exporter/exporter.go
> +			prometheus.BuildFQName(cdnNameSpace, "cdn", "resource_4xx_error_rate"),
回源相关的子系统都设置成 "backsource"
```suggestion
			prometheus.BuildFQName(cdnNameSpace, "backsource", "resource_4xx_error_rate"),
```

2022-08-22 08:02 UTC, LeoQuote commented on exporter/exporter.go
> +			"cdn回源200请求数(次/分钟)",
太多了,而且不能穷举, 请你试试用 label 的方式, 把这些具体状态码请求数的指标归集到一个指标里

2022-08-22 08:02 UTC, LeoQuote commented on exporter/exporter.go
> +			Resource2xxTotalAverage/5,
这些 /5 的操作请统一为一个函数, 以增加可读性, 比如将函数命名为, "转换为 1分钟内的数值", 之类的合理的, 容易理解的名字

2022-08-23 03:47 UTC, LeoQuote commented on exporter/exporter.go
> +		e.cdnCodeDetail.WithLabelValues(domain, "code504").Set(calculateRequestCountPerMin(float64(cdnAccountHealthData.Code504)))
这里的代码能否复用?

2022-08-23 03:48 UTC, LeoQuote commented on exporter/exporter.go
> +				"code",
```suggestion
				"status",
```

2022-08-23 03:49 UTC, LeoQuote commented on exporter/exporter.go
> +				"code",
另外一个也改掉

2022-08-23 03:55 UTC, LeoQuote commented on exporter/exporter.go
> +				"code",
所有的涉及到 http 状态码的变量, 都要从 `code` 改成 `status`

2022-08-31 11:10 UTC, merged